### ISSUE TITLE
Incorrect output for negative margin

### ISSUE THREAD

**Issue by nfrasser** [Faisal-Manzer/postcss-viewport-height-correction#10]
I have an offscreen element like this:

```css
.reveal {
  margin-top: -100vh;
}
```

The plugin outputs this:

```css
.reveal {
    margin-top: -100vh;
    margin-top: -calc(var(--vh, 1vh) * 100);
}
```

But this doesn't work. It should be this:

```css
.reveal {
    margin-top: -100vh;
    margin-top: calc(var(--vh, 1vh) * -100);
}
```
