### ISSUE TITLE
Warning about `from` option

### ISSUE THREAD

**Issue by zumm** [Faisal-Manzer/postcss-viewport-height-correction#18]
I'm using the plugin in my nuxt project, after last nuxt update this warning appeared:

> A PostCSS plugin did not pass the `from` option to `postcss.parse`. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.

**Comment by aweiss-dev** [comment]
Same problem here.

**Comment by Faisal-Manzer** [comment]
I will sure check this and update.

**Comment by momtboy** [comment]
Same problem here.

**Comment by webdev0415** [comment]
Same here

**Comment by yolanare** [comment]
Hi, same for me, did you have time to look into it?

**Comment by zumm** [comment]
For those looking for a solution, I have released a package with similar functionality (and more) - [postcss-better-units](https://www.npmjs.com/package/postcss-better-units).

Here is a config for exactly the same behavior as `postcss-viewport-height-correction`:
```ts
import type { Config } from 'postcss-load-config'
import betterUnits from 'postcss-better-units'

export default {
  plugins: [
    betterUnits([{
      fromUnit: 'vh',
      // custom transformer to add default var value
      transform: value => `calc(var(--vh, 1vh) * ${value})`,
      preserve: 'before'
    }]),
  ],
} satisfies Config
```

```css
main {
  min-height: 100vh;
}
/* becomes */
main {
  min-height: 100vh;
  min-height: calc(var(--vh, 1vh) * 100);
}
```

But i would recommend to take advantage of `dvh` units and fall back to js polyfill if they aren't supported:
```ts
import type { Config } from 'postcss-load-config'
import betterUnits from 'postcss-better-units'

export default {
  plugins: [
    betterUnits([{
      fromUnit: 'dvh',
      toCssVar: '--dvh',
      preserve: 'after',
    }]),
  ],
} satisfies Config
```

```css
main {
  min-height: 100dvh;
}
/* becomes */
main {
  min-height: calc(100 * var(--dvh));
  min-height: 100dvh;
}
```
